# Generated by Django 4.2.4 on 2023-10-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0005_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seguridad.categoria'),
        ),
    ]
