# Generated by Django 4.2.4 on 2023-10-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0006_subcategoria_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategoria',
            old_name='categoria',
            new_name='categoria_relacionada',
        ),
    ]
