# Generated by Django 4.2.4 on 2023-10-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0009_alter_categoria_descripcion_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(to='Seguridad.rol'),
        ),
    ]
