# Generated by Django 4.2.4 on 2023-11-02 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0005_categoria_activo_alter_categoria_descripcion_and_more'),
        ('Seguridad', '0013_alter_usuario_user'),
    ]

    operations = [
    ]
