# Generated by Django 4.2.4 on 2023-11-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0014_alter_rol_nombre'),
        ('Seguridad', '0014_merge_20231102_0116'),
    ]

    operations = [
    ]
