# Generated by Django 4.2.4 on 2023-11-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Contenido', '0002_plantilla_predeterminada_and_more'),
        ('Seguridad', '0015_merge_0014_alter_rol_nombre_0014_merge_20231102_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodecontenido',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Contenido.plantilla'),
        ),
    ]
