# Generated by Django 4.2.4 on 2023-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0019_comentario_respuestacomentario_notificacion_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='num_comentarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contenido',
            name='num_compartidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contenido',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
