# Generated by Django 4.2.4 on 2023-12-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0019_comentario_respuestacomentario_notificacion_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_contenido/'),
        ),
    ]
