# Generated by Django 4.2.4 on 2023-10-20 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('blog', 'Blog (Solo texto)'), ('multimedia', 'Multimedia (Texto + Multimedia)')], max_length=20)),
                ('contenido', models.TextField(default='Texto predeterminado')),
                ('color_principal', models.CharField(default='color_preset', max_length=20)),
                ('titulo_sitio', models.CharField(default='Mi Sitio Web', max_length=100)),
                ('logotipo', models.ImageField(default='default_logo.png', upload_to='logos/')),
                ('contenido_editable', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaPredeterminada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('blog', 'Plantilla solo de texto'), ('imagen', 'Plantilla con imagen')], max_length=20)),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantillas', models.ManyToManyField(default='', to='Gestion_Contenido.plantilla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoEditable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Contenido.plantilla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
