# Generated by Django 4.2.4 on 2023-09-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('blog', 'Blog (Solo texto)'), ('multimedia', 'Multimedia (Texto + Multimedia)')], max_length=20)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
