# Generated by Django 4.2.4 on 2023-10-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Contenido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='predeterminada',
            field=models.BooleanField(default=False),
        ),
    ]
