# Generated by Django 4.2.4 on 2023-10-10 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gestion_Contenido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaPredeterminada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('blog', 'Plantilla solo de texto'), ('imagen', 'Plantilla con imagen')], max_length=20)),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='plantilla',
            name='predeterminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='contenido',
            field=models.TextField(default='Texto predeterminado'),
        ),
        migrations.CreateModel(
            name='PlantillaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
