# Generated by Django 4.2.4 on 2023-10-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Contenido', '0002_plantilla_predeterminada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='color_principal',
            field=models.CharField(default='color_preset', max_length=50),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='tipo',
            field=models.CharField(choices=[('blog', 'Blog (Solo texto)'), ('multimedia', 'Multimedia (Texto + Multimedia)')], max_length=50),
        ),
    ]
