# Generated by Django 4.2.4 on 2023-10-10 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gestion_Contenido', '0002_plantillapredeterminada_plantilla_predeterminada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillausuario',
            name='plantilla',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Gestion_Contenido.plantilla'),
        ),
        migrations.AlterField(
            model_name='plantillausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
