# Generated by Django 4.2.4 on 2023-10-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration): 

    dependencies = [
        ('Gestion_Contenido', '0002_plantillausuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='plantilla',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='plantilla',
            name='tipo',
        ),
        migrations.AddField(
            model_name='plantilla',
            name='campo_temporal',
            field=models.BooleanField(default=False),
        ),
    ]
