# Generated by Django 4.2.4 on 2023-10-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Contenido', '0003_agregar_plantillas_ejemplo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='campo_temporal',
        ),
        migrations.AddField(
            model_name='plantilla',
            name='contenido',
            field=models.TextField(default='Texto predeterminado'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='nombre',
            field=models.CharField(default='Nombre predeterminado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantilla',
            name='tipo',
            field=models.CharField(choices=[('blog', 'Blog (Solo texto)'), ('multimedia', 'Multimedia (Texto + Multimedia)')], default='blog', max_length=20),
            preserve_default=False,
        ),
    ]
