# Generated by Django 4.2.4 on 2023-10-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Contenido', '0004_remove_plantillausuario_plantilla_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantillausuario',
            old_name='plantilla',
            new_name='plantillas',
        ),
    ]
