# Generated by Django 4.2.4 on 2023-10-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Contenido', '0005_rename_plantilla_plantillausuario_plantillas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillausuario',
            name='plantillas',
        ),
        migrations.AddField(
            model_name='plantillausuario',
            name='plantilla',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Gestion_Contenido.plantilla'),
        ),
    ]
