# Generated by Django 4.2.4 on 2023-10-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Contenido', '0006_remove_plantillausuario_plantillas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillausuario',
            name='plantilla',
        ),
        migrations.AddField(
            model_name='plantillausuario',
            name='plantillas',
            field=models.ManyToManyField(to='Gestion_Contenido.plantilla'),
        ),
    ]
