# Generated by Django 4.2.4 on 2023-10-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Contenido', '0007_remove_plantillausuario_plantilla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillausuario',
            name='plantillas',
            field=models.ManyToManyField(default='', to='Gestion_Contenido.plantilla'),
        ),
    ]
