# Generated by Django 4.2.4 on 2023-10-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Contenido', '0008_alter_plantillausuario_plantillas'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='color_principal',
            field=models.CharField(default='color_preset', max_length=20),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='logotipo',
            field=models.ImageField(default='default_logo.png', upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='titulo_sitio',
            field=models.CharField(default='Mi Sitio Web', max_length=100),
        ),
    ]
