# Generated by Django 4.2.4 on 2023-10-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Contenido', '0009_plantilla_color_principal_plantilla_logotipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='contenido_editable',
            field=models.TextField(blank=True, null=True),
        ),
    ]
