# Generated by Django 4.2.4 on 2023-10-11 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gestion_Contenido', '0010_plantilla_contenido_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoEditable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Contenido.plantilla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
