# Generated by Django 4.2.4 on 2023-10-14 12:55

# En models.py
from django.db import migrations
from django.contrib.auth.models import Group, Permission

def create_groups_and_permissions(apps, schema_editor):
    # Obtén los modelos necesarios
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Crear un grupo para editores de plantillas
    group, created = Group.objects.get_or_create(name='Editores de Plantillas')

    # Asignar permisos específicos a este grupo
    permissions = Permission.objects.filter(codename__in=['change_plantilla'])
    group.permissions.set(permissions)

class Migration(migrations.Migration):

    dependencies = [
        # Dependencias de migraciones anteriores si las hay
        ('Gestion_Contenido', '0011_contenidoeditable'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
    ]
