# Generated by Django 4.2.4 on 2023-10-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Contenido', '0012_auto_20231014_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
